/**
 * interpretations.js — Content Database for Chart Interpretation Engine
 * All PLACEHOLDER entries have been replaced with real content.
 */

export const CONTENT = {

  lagna: {
    Aries: "Aries Lagna is ruled by Mars — cardinal fire, the first arising of individual will. The attention moves outward naturally and with directness. Energy concentrates at the point of action rather than deliberation. This Lagna tends to meet the world head-on and expects the world to respond in kind. The learning of Aries Lagna is that genuine courage includes the willingness to pause — that speed of action and clarity of direction are not always the same thing. The lord of this Lagna is Mars, and its placement in the chart shows where this directness and drive find their primary channel of expression.",

    Taurus: "Taurus Lagna is ruled by Venus — fixed earth, the principle of stable, embodied presence. The attention orients toward what endures — what can be built, tasted, held, and kept. Patience is native to this Lagna; change happens only when its necessity has been genuinely absorbed. There is often a deep appreciation for beauty and comfort, and a corresponding resistance to disruption of what has been established. The learning of Taurus Lagna is that genuine security does not come from what is accumulated but from what is known within. The lord of this Lagna is Venus, and its placement shows how this orientation toward beauty and stability expresses itself through specific life arenas.",

    Gemini: "Gemini Lagna is ruled by Mercury — dual air, the principle of perception, connection, and communication. The attention is quick, curious, and relational. This Lagna processes the world through language, pattern, and the delight of making connections between apparently unlike things. There can be a facility with words and ideas that makes learning come naturally and communication feel native. The learning of Gemini Lagna is the refinement of this intelligence toward genuine discrimination — using the mind's quickness in service of what is real rather than simply what is stimulating. The lord of this Lagna is Mercury, and its placement shows where this curiosity and communicative capacity find their most natural expression.",

    Cancer: "Cancer Lagna is ruled by the Moon — cardinal water, the principle of feeling, belonging, and the need for genuine security. The attention is sensitive and receptive; the environment shapes experience more directly here than in most Lagnas. There is often a natural empathy and a strong orientation toward family, home, and the people who constitute one's inner circle. The world is encountered through feeling first. The learning of Cancer Lagna is that genuine inner security is found within rather than in the constancy of what is outside. The lord of this Lagna is the Moon, and its placement shows where emotional nourishment and the need for belonging find their primary expression in this life.",

    Leo: "Leo Lagna is ruled by the Sun — fixed fire, the principle of inherent dignity and authentic self-expression. The attention carries a natural quality of confidence and warmth; there is often a pull toward being seen, acknowledged, and genuinely recognised. Leadership comes naturally to this Lagna when it is grounded, and genuine generosity is one of its finest qualities. The learning of Leo Lagna is the distinction between performance and authenticity — between seeking recognition and simply being what one genuinely is, which is the only source of real dignity. The lord of this Lagna is the Sun, and its placement shows where this drive toward self-expression and authentic authority finds its most natural channel.",

    Virgo: "Virgo Lagna is ruled by Mercury — dual earth, the principle of discrimination, refinement, and honest service. The attention is precise and analytical; the world is encountered as something that can always be understood more clearly and improved more carefully. There is often a natural capacity for detailed work, a high standard applied to everything, and a genuine orientation toward being useful rather than merely impressive. The learning of Virgo Lagna is turning this same precise attention inward with compassion rather than criticism — understanding that the standard applied to the world is also being applied to oneself, and that both deserve honest but gentle seeing. The lord of this Lagna is Mercury, and its placement shows where this discriminating intelligence and capacity for refinement find their primary expression.",

    Libra: "Libra Lagna is ruled by Venus — cardinal air, the principle of balance, harmony, and conscious relationship. The attention seeks fairness; decisions are often held until all sides have been genuinely considered. There is a natural aesthetic sensibility and a strong orientation toward how things relate to each other — whether in design, in relationships, or in ideas. The learning of Libra Lagna is developing the capacity to act from one's own centre — to know clearly what one stands for — rather than remaining perpetually in the weighing. Genuine balance cannot be found by endlessly considering others' positions; it requires first knowing one's own. The lord of this Lagna is Venus, and its placement shows where this relational sensitivity and search for harmony find their most natural expression.",

    Scorpio: "Scorpio Lagna is ruled by Mars — fixed water, the principle of depth, transformation, and penetrating awareness. The attention moves toward what is underneath the surface — toward what is real, what is hidden, what other people do not see or say. This Lagna does not remain on the surface of anything for long. There is often an intensity to the presence and a natural perceptiveness that can be both a gift and a challenge in relationship. The learning of Scorpio Lagna is that the capacity to see through everything must eventually be turned toward genuine transformation of oneself rather than remaining in the position of the observer who penetrates but does not allow themselves to be fully changed. The lord of this Lagna is Mars, and its placement shows where this depth and transformative drive find their most natural channel.",

    Sagittarius: "Sagittarius Lagna is ruled by Jupiter — dual fire, the principle of meaning, expansion, and the search for what is genuinely true. The attention orients toward the horizon — toward philosophy, teaching, travel, and the wider implications of things. There is a natural optimism and a genuine love of learning that can make this Lagna one of the most enthusiastic seekers. The learning of Sagittarius Lagna is that genuine wisdom is not found only in the distance or in grand philosophical frameworks — that the present moment and its specific responsibilities contain as much truth as any distant horizon. The lord of this Lagna is Jupiter, and its placement shows where this search for meaning and expansive quality find their most natural expression.",

    Capricorn: "Capricorn Lagna is ruled by Saturn — cardinal earth, the principle of structure, discipline, and sustained purposeful effort. The attention is patient and systematic; the world is encountered as a place where things are built slowly and kept through integrity rather than speed or luck. There is often a seriousness to this Lagna that deepens rather than lightens with age — Capricorn Lagna tends to improve over time as Saturn's demands become more familiar and more genuinely met. The learning of Capricorn Lagna is that what is built outward must be matched by what is developed inward — that structure without inner depth eventually becomes its own limitation. The lord of this Lagna is Saturn, and its placement shows where this disciplined, building quality finds its most natural expression.",

    Aquarius: "Aquarius Lagna is ruled by Saturn — fixed air, the principle of collective orientation, principle, and the longer arc of time and purpose. The attention orients toward what serves something larger than the individual — toward ideas, principles, communities, and structures that outlast the single life. There is often a quality of detachment that can appear as genuine impartiality or, in its more challenged expression, as distance from the immediate and the personal. The learning of Aquarius Lagna is that genuine service to the collective does not require the denial of personal feeling — and that principles without compassion can become as rigid as the structures they seek to replace. The lord of this Lagna is Saturn, and its placement in the chart shows where this collective orientation and principled quality find their most natural channel of expression.",

    Pisces: "Pisces Lagna is ruled by Jupiter — dual water, the principle of expansion, compassion, and permeability to the subtle. The attention is fluid and empathetic; the boundary between self and world is more permeable here than in most Lagnas. There is often a natural sensitivity to what is not said, a capacity for genuine compassion, and an orientation toward the spiritual and the transcendent. The 12th house of dissolution rules the physical body in this Lagna, making the quality of sleep, retreat, and inner practice particularly significant for physical and mental wellbeing. The learning of Pisces Lagna is that genuine transcendence does not require the abandonment of discernment — and that compassion which loses itself entirely in others eventually has nothing left to give. The lord of this Lagna is Jupiter, and its placement significantly shapes how this expansive, empathetic quality is focused or diffused in this life.",
  },

  planetInHouse: {
    Sun: {
      1:  "The Sun in the 1st house places the self-principle at the centre of the life's expression. Identity tends to be strong and clearly defined, or strongly tested until it becomes so. There is often a native need for authenticity — for being seen as one genuinely is. The sadhana direction is genuine self-knowledge rather than self-promotion.",
      2:  "The Sun in the 2nd house illuminates speech, family lineage, and accumulated resources. The father or paternal lineage may carry particular significance in shaping the native's relationship with wealth and values. There is often a strong sense of family identity and a capacity for authoritative expression. The sadhana direction is developing the capacity to speak and accumulate from genuine inner richness rather than from the need to establish status.",
      3:  "The Sun in the 3rd house brings courage and solar energy into communication, effort, and the relationship with siblings. There is typically a directness in expressing one's views and a willingness to act on one's own initiative. The sadhana direction is developing the capacity to express one's genuine perspective with both courage and consideration.",
      4:  "The Sun in the 4th house brings the self-principle into the domain of home, mother, and inner security. Home environments may carry themes of authority or high standards. The Sun is not in its strongest position below the horizon. The sadhana direction is learning to build genuine inner security rather than needing the home to constantly reflect and validate the sense of self.",
      5:  "The Sun in the 5th house illuminates intelligence, creativity, children, and the soul's accumulated merit. Creativity tends to be expressive and confident. The sadhana direction is offering the fruits of this creativity and intelligence without the attachment to recognition — the Sun's genuine gift in the 5th is most powerful when it shines for the joy of shining.",
      6:  "The Sun in the 6th house, an Upachaya house, often indicates strong competitive drive, the capacity to overcome adversity, and genuine resilience. Health may be an arena of particular attention. The sadhana direction is directing this competitive and overcoming energy toward genuinely worthy goals.",
      7:  "The Sun in the 7th house places the self-principle directly into the arena of partnership and the public face. The partner may carry solar qualities — authority or strong personality. The sadhana direction is developing the capacity for genuine mutuality — allowing the partner to be as fully present and real as oneself.",
      8:  "The Sun in the 8th house places the solar principle into the domain of transformation and the hidden. There can be significant life experiences involving loss or sudden change. Interest in what is hidden — research, psychology — is common. The sadhana direction is developing genuine equanimity in the face of change.",
      9:  "The Sun in the 9th house illuminates dharma, the father principle, and higher wisdom. This is a generally strong placement — the 9th is a Kona house and the Sun here carries natural grace toward the domains of philosophy and righteous action. The sadhana direction is developing genuine wisdom rather than merely holding correct positions.",
      10: "The Sun in the 10th house is its Digbala position — directional strength. Career tends to carry genuine solar themes — authority, organisation, or public responsibility. The sadhana direction is carrying genuine inner authenticity into the public role rather than allowing the public role to substitute for genuine selfhood.",
      11: "The Sun in the 11th house illuminates gains, aspirations, elder siblings, and the social network. Long-term goals tend to carry solar energy and a natural capacity to attract networks centred around achievement or public purpose. The sadhana direction is ensuring that aspirations serve something genuinely meaningful.",
      12: "The Sun in the 12th house places the solar principle in the domain of dissolution and what is hidden from the ordinary world. There may be themes of spiritual seeking, work done in private, or a father who was physically distant. The sadhana direction is learning that the solar light in the 12th is most genuine when it illuminates the inner world.",
    },
    Moon: {
      1:  "The Moon in the 1st house places the mind and emotional body at the centre of the life's expression. The inner world expresses readily through the outer — emotional states are transparent in the body and the public face. There is often a deep sensitivity and natural empathy. The sadhana direction is developing genuine emotional clarity so that the Moon's sensitivity becomes a resource for genuine understanding rather than a source of constant reactivity.",
      2:  "The Moon in the 2nd house brings emotional themes into the domain of speech, family, and resources. The voice may carry a natural nourishing quality. The mother's influence on values and the relationship with wealth may be significant. The sadhana direction is developing genuine inner nourishment that is not dependent on the constancy of outer resources.",
      3:  "The Moon in the 3rd house moves the mind through communication and short journeys. There is often a restlessness to the mental activity here — the mind seeks stimulation. Siblings may carry significant emotional weight. The sadhana direction is channelling this mental movement toward genuine expression rather than anxious busyness.",
      4:  "The Moon in the 4th house is its Digbala placement. Emotional roots tend to run deep and the home carries genuine significance as a place of refuge. The mother is often a central figure in shaping the native's emotional world. The sadhana direction is developing the inner home — the stillness within — as the primary source of emotional security.",
      5:  "The Moon in the 5th house moves the mind into creativity, intelligence, and children. Intuition tends to be heightened. Creative expression may have a nourishing quality — the native creates from feeling rather than from concept. The sadhana direction is developing the capacity to offer the fruits of this intuition without emotional attachment to how they are received.",
      6:  "The Moon in the 6th house places emotional and mental sensitivity in the domain of obstacles and service. The native may have a strong natural capacity for healing or care-giving. The mind can be prone to emotional rumination around problems. The sadhana direction is developing the capacity to engage with difficulty from a place of steady witnessing.",
      7:  "The Moon in the 7th house brings the emotional world directly into the arena of partnership. The partner reflects the native's inner emotional life in significant ways. The sadhana direction is developing the capacity to bring genuine inner emotional clarity to relationships rather than looking to partnership to resolve what can only be met within.",
      8:  "The Moon in the 8th house places the mind in the domain of depth and transformation. Intuition can be very strong. Emotional life can be intense and the inner world may carry material that requires sustained honest engagement. The sadhana direction is developing genuine emotional stability that does not depend on the absence of depth.",
      9:  "The Moon in the 9th house moves the mind toward philosophy, dharma, and the teacher. The native's sense of inner security is nourished by connection to a meaningful framework. The sadhana direction is deepening this orientation toward wisdom — allowing it to become genuinely lived rather than merely intellectually held.",
      10: "The Moon in the 10th house places the emotional body in the domain of career and public life. There is often a natural popularity or a capacity to sense what people need. The sadhana direction is grounding the capacity to serve and to be publicly visible in genuine inner stability.",
      11: "The Moon in the 11th house places emotional significance in the domain of aspirations and social networks. Friendships and community carry genuine emotional nourishment. The sadhana direction is ensuring that the sense of community serves genuine connection rather than becoming a substitute for inner security.",
      12: "The Moon in the 12th house moves the mind toward the interior and the subtle. Sleep and dreams may be particularly significant. There is often a natural orientation toward contemplative practice. The sadhana direction is honouring this natural interiority — developing genuine contemplative practice.",
    },
    Mars: {
      1:  "Mars in the 1st house places energy, drive, and directed force at the centre of the life's expression. Physical vitality is typically strong and the body leads — action tends to come before deliberation. The will tends to be strong and the native meets resistance with increased effort. The sadhana direction is developing the capacity to direct this energy consciously rather than reactively.",
      2:  "Mars in the 2nd house directs energy into speech, family resources, and the accumulation of wealth. Speech tends to be direct, sometimes cutting — words carry force. Energy goes into building and defending what has been accumulated. The sadhana direction is developing precision and care in speech — using the directness of Mars to speak truthfully rather than forcefully.",
      3:  "Mars in the 3rd house places courage, initiative, and drive into communication and effort. There is typically a willingness to act on one's own initiative and a strong competitive streak. The 3rd is an Upachaya house — Mars gains strength here with effort over time. The sadhana direction is channelling this drive into genuine creative output and honest communication.",
      4:  "Mars in the 4th house brings energy and assertion into the domain of home, mother, and inner life. The home environment may carry a quality of activity, tension, or the ongoing effort of building. The sadhana direction is developing genuine inner stillness — the quality of home that Mars in the 4th is genuinely seeking.",
      5:  "Mars in the 5th house directs energy into creativity, intelligence, and children. Creative expression tends to be forceful and driven. Intelligence is sharp, quick, and inclined toward analysis and strategy. The sadhana direction is offering this creative and intellectual energy without the need for it to prove capability.",
      6:  "Mars in the 6th house is one of Mars's stronger positions — the 6th is an Upachaya house. The capacity to compete, to overcome obstacles, to sustain effort in the face of difficulty — all these are enhanced. The sadhana direction is ensuring this considerable energy is directed toward genuinely worthy challenges.",
      7:  "Mars in the 7th house places energy, assertion, and the principle of force into the arena of partnership. The partner may carry Martian qualities — strength, directness, or a competitive nature. The sadhana direction is developing the capacity to bring genuine courage and strength to partnership without needing it to be a competition.",
      8:  "Mars in the 8th house directs energy into the domain of transformation and the hidden. There can be an intensity in engaging with difficult truths — research, investigation, or confrontation of what cannot be controlled. The sadhana direction is directing this penetrating energy toward genuine understanding of what is hidden within oneself.",
      9:  "Mars in the 9th house directs drive and energy into dharma and the relationship with teachers and wisdom traditions. This can be a strong placement when dignified — the capacity to act from genuine principle. The sadhana direction is ensuring the energy directed toward dharma serves genuine right action rather than the assertion of one's own version of rightness.",
      10: "Mars in the 10th house is its Digbala placement — directional strength. The energy and drive of Mars reach their most natural expression in career and public action. Career may connect to medicine, engineering, military, law enforcement, sport, or administration. The sadhana direction is carrying genuine integrity into this public force.",
      11: "Mars in the 11th house directs drive and competitive energy toward gains and the fulfilment of long-term goals. The 11th is an Upachaya house — Mars gains strength here with time and effort. The sadhana direction is ensuring this considerable drive is oriented toward goals that are genuinely meaningful.",
      12: "Mars in the 12th house directs energy toward what is hidden, foreign, or oriented away from conventional worldly engagement. The challenge is that the energy may be difficult to access in ordinary life situations. The sadhana direction is consciously directing this hidden energy toward genuine spiritual practice or meaningful service.",
    },
    Mercury: {
      1:  "Mercury in the 1st house places intelligence, communication, and discriminating awareness at the centre of the life's expression. The personality tends to be curious, articulate, and analytically oriented — the mind leads. The sadhana direction is developing genuine Viveka — discriminating wisdom — alongside the facility for analysis.",
      2:  "Mercury in the 2nd house brings intelligence and communicative facility into the domain of speech, resources, and family values. Speech is typically a key resource — the ability to communicate clearly can generate real financial and social value. The sadhana direction is ensuring the facility with speech serves genuine understanding and honest communication.",
      3:  "Mercury in the 3rd house is in its natural domain — communication, writing, siblings, and the expression of intelligence in the immediate environment. Writing, speaking, and all forms of short-form communication tend to be areas of genuine strength. The sadhana direction is deepening this communicative facility toward genuine discriminating wisdom.",
      4:  "Mercury in the 4th house brings intellectual themes into the domain of home, mother, and inner life. The home may carry a quality of learning — books and the ongoing stimulation of the curious mind. Inner life is active and analytical. The sadhana direction is developing the capacity for genuine inner stillness alongside the natural intellectual busyness.",
      5:  "Mercury in the 5th house brings intelligence and communicative skill into the domain of creativity and speculative intelligence. There is often a natural gift for analysis in creative contexts. The sadhana direction is using this analytical and creative intelligence in service of genuine understanding rather than clever performance.",
      6:  "Mercury in the 6th house directs analytical intelligence toward problem-solving, health, and service. Work involving detailed analysis or precise communication in healthcare, law, or research tends to suit this placement. The sadhana direction is ensuring analytical precision is applied as generously to understanding others as to identifying their errors.",
      7:  "Mercury in the 7th house places intellectual and communicative quality into the domain of partnership. The partner tends to carry Mercurial qualities. Business communication and negotiation may be significant arenas. The sadhana direction is developing the capacity for genuine emotional presence alongside the communicative facility.",
      8:  "Mercury in the 8th house directs the intellect toward research and the domain of transformation. There is often a natural pull toward investigative work — uncovering what is not on the surface. The sadhana direction is directing this investigative intelligence toward genuine understanding of the nature of transformation.",
      9:  "Mercury in the 9th house orients the intellect toward teaching, higher learning, philosophy, publishing, or law. There may be a natural capacity for communicating wisdom — making complex ideas clear. The sadhana direction is developing the depth of understanding that genuine wisdom requires alongside communicative facility.",
      10: "Mercury in the 10th house places intelligence and communicative skill in the domain of career and public engagement. Career typically connects to communication, analysis, writing, information, or business. The sadhana direction is ensuring the considerable communicative capacity serves genuine purpose.",
      11: "Mercury in the 11th house directs intellectual and communicative capacity toward gains, networks, and aspirations. There may be gains through intellectual work, communication networks, or information-based activities. The sadhana direction is ensuring these networks serve genuinely worthwhile purposes.",
      12: "Mercury in the 12th house moves the intellect toward the contemplative, the foreign, and what is hidden from ordinary social engagement. Writing done in private may be particularly meaningful. The sadhana direction is honouring this natural contemplative orientation of the mind.",
    },
    Jupiter: {
      1:  "Jupiter in the 1st house is its Digbala placement — directional strength. The personality carries a natural philosophical quality and genuine warmth and generosity. Wisdom and the search for meaning orient the life's expression. The sadhana direction is ensuring this natural expansiveness and wisdom serves genuine understanding rather than comfortable belief.",
      2:  "Jupiter in the 2nd house brings wisdom, expansiveness, and the principle of meaningful abundance into the domain of speech, family, and resources. Speech tends to carry a quality of wisdom or teaching. Wealth may accumulate through Jupiterian fields. The sadhana direction is ensuring that abundance is understood as a condition to be shared rather than accumulated.",
      3:  "Jupiter in the 3rd house brings philosophical weight and expansiveness into the domain of communication, effort, and siblings. Effort and communication carry genuine philosophical depth. The sadhana direction is developing the capacity for precise, courageous action alongside the philosophical depth.",
      4:  "Jupiter in the 4th house brings wisdom, learning, and genuine inner abundance into the domain of home, mother, and inner life. The home tends to carry a quality of learning and generosity. Inner peace tends to be a genuine resource. The sadhana direction is developing genuine inner stability that does not depend on comfortable circumstances.",
      5:  "Jupiter in the 5th house is one of Jupiter's own domains — the 5th is a Kona house and Jupiter here carries genuine grace. There is often a natural teaching capacity — the ability to communicate wisdom in ways that inspire. The sadhana direction is offering this wisdom in genuine service rather than guarding it as a source of status.",
      6:  "Jupiter in the 6th house brings the expansive and benefic principle into a domain of challenge and service. Jupiter here can carry genuine grace toward healing work and service to those who are struggling. The sadhana direction is learning to offer genuine wisdom and care while developing the capacity to set appropriate boundaries.",
      7:  "Jupiter in the 7th house brings wisdom, expansiveness, and genuine growth into the arena of partnership. The partner tends to carry Jupiterian qualities — wisdom or a broad and generous perspective. The sadhana direction is ensuring the expansiveness of Jupiter in partnership is matched by genuine emotional depth.",
      8:  "Jupiter in the 8th house brings the principle of grace and wisdom into the domain of transformation and the hidden. Jupiter here can bring genuine grace into the arena of transformation — finding meaning in what others experience as loss or disruption. The sadhana direction is using this gift to genuinely understand the nature of change.",
      9:  "Jupiter in the 9th house is its most natural placement — the 9th is Dharmabhava and Jupiter is the natural significator of dharma. Teaching, philosophy, father, and the deep questions of meaning are all illuminated with genuine grace here. The sadhana direction is ensuring that the considerable wisdom available is genuinely lived.",
      10: "Jupiter in the 10th house places wisdom, expansiveness, and meaningful purpose into the domain of career and public life. Career tends to carry Jupiterian themes — counselling, law, teaching, finance, or philosophy. The sadhana direction is ensuring the public role is understood as genuine service rather than as a platform.",
      11: "Jupiter in the 11th house brings expansiveness and the principle of genuine abundance into the domain of gains, aspirations, and social networks. Gains tend to come through Jupiterian fields and the capacity to inspire and connect others. The sadhana direction is ensuring abundance flows through rather than accumulating.",
      12: "Jupiter in the 12th house places the planet of wisdom and liberation in the house of liberation. Spiritual seeking, contemplative practice, and charitable expenditure may be significant. The sadhana direction is honouring this natural pull toward the transcendent by developing genuine practice rather than merely philosophical familiarity with liberation.",
    },
    Venus: {
      1:  "Venus in the 1st house places beauty, relational sensitivity, and the principle of refined experience at the centre of the life's expression. The body tends toward aesthetics and the personality carries a relational quality — people feel welcomed. The sadhana direction is developing genuine discernment alongside the natural appreciation for beauty and relationship.",
      2:  "Venus in the 2nd house is in one of its natural domains. Resources may accumulate through beauty, art, design, or pleasure. Speech tends to carry a pleasing quality. The sadhana direction is developing genuine inner values that do not depend on the continuous accumulation of beautiful things.",
      3:  "Venus in the 3rd house brings creativity, aesthetic sensibility, and relational quality into the domain of communication and effort. There is often a genuine gift for creative communication. The sadhana direction is using this creative and relational facility in service of genuine expression.",
      4:  "Venus in the 4th house is its Digbala placement. The home tends to carry genuine beauty and comfort. Inner life has a quality of genuine contentment and the capacity for genuine happiness. The sadhana direction is developing genuine inner beauty — the capacity to find and appreciate real beauty in the depths of experience.",
      5:  "Venus in the 5th house brings creativity, romance, and the principle of beautiful experience into the domain of intelligence, children, and past merit. Artistic expression tends to be genuine and potentially significant. The sadhana direction is offering this creative and aesthetic gift in genuine service.",
      6:  "Venus in the 6th house places the principle of beauty and relationship in a domain of challenge and service. Relationships or finances may involve difficulty or require conscious effort. There can be a genuine capacity for working in aesthetic healing. The sadhana direction is developing the capacity to maintain genuine beauty and relational grace in the face of difficulty.",
      7:  "Venus in the 7th house is in its natural domain. Partnership is a central arena of life experience and genuine significance. The partner tends to carry Venusian qualities — beauty, refinement, or a gracious manner. The sadhana direction is developing genuine depth of relationship alongside the natural harmony and beauty.",
      8:  "Venus in the 8th house places the principle of beauty and relationship in the domain of depth and transformation. There can be an interweaving of sensuality and the occult. The sadhana direction is allowing the transformative quality of the 8th to genuinely deepen Venus's appreciation of beauty.",
      9:  "Venus in the 9th house places the principle of beauty and refined experience in the domain of dharma and higher wisdom. Art as dharma may be a significant theme. The sadhana direction is understanding that genuine beauty is not separate from genuine truth.",
      10: "Venus in the 10th house places the principle of beauty, relationship, and refined experience in the domain of career and public life. Career tends to carry Venusian themes — art, beauty, design, diplomacy, or entertainment. The sadhana direction is grounding this public beauty in genuine values.",
      11: "Venus in the 11th house brings beauty, relational grace, and the principle of refined pleasure into the domain of gains, aspirations, and social networks. Social networks may carry a quality of pleasure and aesthetic appreciation. The sadhana direction is ensuring that pleasures and connections cultivated serve genuine nourishment.",
      12: "Venus in the 12th house places the principle of beauty and relationship in the domain of dissolution and liberation. Pleasure and relationship may carry a private or hidden quality. The sadhana direction is discovering that genuine beauty and genuine liberation are not separate.",
    },
    Saturn: {
      1:  "Saturn in the 1st house places discipline, structure, and the principle of earned development at the centre of the life's expression. The body and personality carry a quality of seriousness that deepens rather than lightens with age. Saturn in the 1st tends to improve significantly with age. The sadhana direction is engaging consciously with Saturn's demand for genuine inner development — not resisting the weight but understanding that the weight is the practice.",
      2:  "Saturn in the 2nd house brings discipline, austerity, and the principle of earned accumulation into the domain of speech, family, and resources. Speech may be slow, careful, or economical. Wealth accumulates through sustained, disciplined effort. The sadhana direction is developing genuine inner richness — learning that what is genuinely valuable is earned through character.",
      3:  "Saturn in the 3rd house places discipline and sustained effort into the domain of communication, effort, and siblings. The 3rd is an Upachaya house — Saturn gains strength here with time. Writing or communication requiring sustained discipline over many years may produce genuinely significant results. The sadhana direction is engaging patiently with the long arc of Saturn's developmental demand.",
      4:  "Saturn in the 4th house places structure and discipline into the domain of home, mother, and inner life. Home environments may carry a quality of restriction or formal structure. Real estate or property may be acquired through sustained effort over time. The sadhana direction is building genuine inner security through sustained inner work.",
      5:  "Saturn in the 5th house brings discipline and patient development into the domain of intelligence, creativity, and children. Intelligence tends to be methodical and thorough rather than quick and brilliant. Creative expression may require sustained discipline but can produce work of genuine substance. The sadhana direction is developing patience with the slow unfolding that Saturn in the 5th requires.",
      6:  "Saturn in the 6th house is one of Saturn's stronger positions — the 6th is an Upachaya house. The capacity for methodical, disciplined service and the long-term defeat of obstacles through patient strategy are enhanced. The sadhana direction is directing Saturn's considerable disciplined capacity toward genuinely worthy service.",
      7:  "Saturn in the 7th house is its Digbala placement — directional strength. Partnerships carry themes of responsibility, depth, and karmic significance. The partner may be older or serious. What partnerships lack in spontaneous ease, they can carry in genuine depth and durability. The sadhana direction is bringing genuine integrity and patience to partnership.",
      8:  "Saturn in the 8th house places discipline and structure into the domain of transformation, longevity, and the hidden. Longevity may be indicated. Research requiring sustained methodical effort over long periods may suit this placement. The sadhana direction is allowing the transformative demands of the 8th house to be met with Saturn's genuine capacity for disciplined endurance.",
      9:  "Saturn in the 9th house places discipline and the principle of earned wisdom into the domain of dharma, philosophy, father, and teacher. Dharma is approached methodically — there is a preference for structured traditions and disciplined practice. The sadhana direction is engaging genuinely and patiently with the structured spiritual tradition that Saturn in the 9th is drawn to.",
      10: "Saturn in the 10th house, an Upachaya house, builds real and lasting authority through sustained disciplined engagement. Career tends to carry themes of authority, administration, or sustained public effort. What is built in career may come slowly but tends to last. The sadhana direction is ensuring the considerable authority Saturn eventually builds is used in genuine service.",
      11: "Saturn in the 11th house places discipline and sustained effort into the domain of aspirations, networks, and the fulfilment of long-term goals. The 11th is an Upachaya house — Saturn gains genuine strength here with time. Gains tend to come through large organisations or long-term projects. The sadhana direction is engaging patiently with the long arc of Saturn's developmental demand in the domain of aspiration.",
      12: "Saturn in the 12th house places discipline and the principle of earned liberation into the domain of dissolution, solitude, and the transcendent. The 12th is the house of Moksha and Saturn here can indicate a genuine orientation toward the disciplines of liberation. The sadhana direction is honouring Saturn's genuine call in the 12th — developing the discipline of genuine inner renunciation.",
    },
    Rahu: {
      1:  "Rahu in the 1st house places the principle of amplified desire and unfamiliar direction at the centre of the life's expression. There is often an unusual or intense quality to the self-presentation. The personality tends to express itself with an amplified, sometimes obsessive quality. The sadhana direction is engaging consciously with Rahu's pull toward expansion while developing genuine inner grounding.",
      2:  "Rahu in the 2nd house amplifies desires around wealth, speech, family lineage, and the accumulation of resources. There may be unusual patterns around food or accumulation. Speech may be amplified or unconventional. The sadhana direction is developing genuine inner values — distinguishing between what is genuinely worth accumulating and what is merely amplified desire.",
      3:  "Rahu in the 3rd house is in an Upachaya position — it gains strength here. There is typically a strong ambition in the domain of communication, media, or self-expression. Unusual or unconventional forms of communication may emerge. The sadhana direction is directing this considerable communicative ambition toward genuine expression.",
      4:  "Rahu in the 4th house amplifies and intensifies the domain of home, mother, and inner life. The home environment may carry unusual or foreign themes. Inner life may feel intense or unsettled. The sadhana direction is developing genuine inner stability — recognising that what Rahu in the 4th is ultimately seeking is the genuine home within.",
      5:  "Rahu in the 5th house amplifies desire and unconventional quality in the domain of intelligence, creativity, children, and past-life connections. There is often a genuinely unconventional intelligence — the ability to make connections that others miss. The sadhana direction is directing this amplified creative energy toward genuine purpose.",
      6:  "Rahu in the 6th house is in an Upachaya position — it gains strength here. There is an unusual capacity to overcome obstacles. Work in foreign environments, healthcare, or law may suit this placement. The sadhana direction is directing this considerable obstacle-overcoming capacity toward genuinely worthy challenges.",
      7:  "Rahu in the 7th house amplifies the desire for partnership and brings unusual or foreign elements into the arena of relationship. The partner may carry unusual or amplified qualities. The sadhana direction is developing genuine relational depth alongside the amplified relational desire.",
      8:  "Rahu in the 8th house amplifies desire around transformation, the occult, inheritance, and what is hidden. There may be a genuinely compelling pull toward research into the hidden or deeper dimensions of reality. The sadhana direction is directing this pull toward the hidden toward genuine understanding.",
      9:  "Rahu in the 9th house amplifies and intensifies the relationship with dharma, teacher, father, and higher wisdom. There may be unusual or foreign elements in the spiritual or philosophical path. The sadhana direction is approaching the genuine search for wisdom with genuine discernment.",
      10: "Rahu in the 10th house amplifies ambition in career and public life. There is typically a strong and sometimes consuming drive toward public significance and professional achievement. Unusual or rapid rise is possible. The sadhana direction is ensuring the considerable public ambition is oriented toward genuinely meaningful contribution.",
      11: "Rahu in the 11th house amplifies desire for gains and the fulfilment of ambitions. Gains may come through unusual networks, foreign connections, or unconventional fields. The 11th is a house where Rahu tends to be relatively comfortable. The sadhana direction is ensuring the drive toward the fulfilment of ambitions serves genuinely meaningful purposes.",
      12: "Rahu in the 12th house amplifies the pull toward the hidden, foreign, and transcendent. Foreign travel, unusual connections to institutions or spiritual paths, and hidden desires may be significant themes. The sadhana direction is approaching the genuine pull toward liberation with the patient discipline that genuine liberation requires.",
    },
    Ketu: {
      1:  "Ketu in the 1st house carries a quality of detachment or unusual selfhood at the centre of the life's expression. There may be a sense of not quite inhabiting one's own identity in the conventional way — the self-sense carries Ketu's quality of dissolution and completion. The sadhana direction is working with Ketu's gift of natural detachment from the self-construct as genuine spiritual material.",
      2:  "Ketu in the 2nd house carries themes of past-life completion in the domains of speech, family lineage, and accumulated resources. The relationship with family of origin may carry a quality of completion. Speech may carry a quality of detachment or unusual depth. The sadhana direction is using Ketu's gift of genuine non-attachment in the domain of speech and resources.",
      3:  "Ketu in the 3rd house carries themes of past-life completion in the domains of communication, siblings, and effort in the immediate environment. Communication may carry a quality of unusual precision or detachment. The sadhana direction is using Ketu's precision in the domain of communication to express what is genuinely true and essential.",
      4:  "Ketu in the 4th house carries themes of past-life completion in the domains of home, mother, and inner security. Inner life may be genuinely rich in ways that are not easily shared. Spiritual practices oriented toward inner stillness may feel native. The sadhana direction is developing genuine inner home through genuine contemplative practice.",
      5:  "Ketu in the 5th house carries themes of past-life completion in the domains of intelligence, creativity, children, and past-life merit. Intuitive and spiritual intelligence may be particularly strong. The sadhana direction is using Ketu's gift of intuitive insight in genuine service rather than holding it as personal achievement.",
      6:  "Ketu in the 6th house carries themes of past-life completion in the domain of obstacles, health, and service. There may be an unusual relationship with health. The capacity to dissolve obstacles rather than fighting them directly may be a genuine gift. The sadhana direction is using Ketu's dissolving quality in the domain of obstacles and service.",
      7:  "Ketu in the 7th house carries themes of past-life completion in the domain of partnership and the encounter with the other. Partnership may carry unusual or karmic dimensions. The sadhana direction is using Ketu's gift of detachment in the domain of relationship — developing genuine partnership based on what is real between two people.",
      8:  "Ketu in the 8th house carries themes of past-life completion in the domain of transformation and the hidden. Intuition around the deeper dimensions of reality may be particularly strong. Research into genuinely esoteric subjects may feel native. The sadhana direction is using what has been developed across lifetimes in service of genuine understanding.",
      9:  "Ketu in the 9th house carries themes of past-life completion in the domain of dharma, wisdom, and the relationship with teacher and tradition. The spiritual path may carry a quality of departure from familiar religious forms. The sadhana direction is engaging with the genuine spiritual maturity that Ketu in the 9th indicates — moving beyond the framework toward the reality the framework was always pointing at.",
      10: "Ketu in the 10th house carries themes of past-life completion in the domain of career and public action. The relationship with public recognition may carry a quality of detachment or completion. Service, spiritual work, or creative engagement that does not require public recognition may feel more genuinely aligned. The sadhana direction is developing the capacity to act fully without the need for action to be publicly recognised.",
      11: "Ketu in the 11th house carries themes of past-life completion in the domain of gains, aspirations, and social networks. The relationship with worldly gains and the fulfilment of conventional ambitions may carry a quality of genuine non-attachment. The sadhana direction is using Ketu's gift of genuine non-attachment in the domain of gains.",
      12: "Ketu in the 12th house is in its most natural domain. Ketu here carries a deep and genuine orientation toward Moksha. Spiritual practice, solitude, and retreat may feel deeply natural. The capacity for genuine inner stillness may be significant. The sadhana direction is honouring the natural pull toward liberation that Ketu in the 12th indicates — engaging with genuine spiritual practice.",
    },
  },

  dashaReadings: {
    Sun: "The Sun Dasha asks the native to engage directly with questions of identity, authenticity, and dharmic direction. Over its six years, the themes of the natal Sun — its sign, house, dignity, and aspects — become activated and primary. Career, father, authority figures, and the question of what it means to genuinely be oneself rather than to perform a version of oneself tend to become central. The period often brings encounters with authority figures who either support this development or test it. The sadhana direction is ensuring that what is expressed publicly in this period is genuinely aligned with what is real within.",

    Moon: "The Moon Dasha asks the native to engage deeply with the emotional and relational world — with the quality of the inner life and with what genuinely nourishes. Over its ten years, the natal Moon's sign, house, dignity, and aspects are activated and become primary themes. Home, mother, mind, and inner security come to the foreground. Fluctuation is inherent to the Moon's nature — this period often involves significant changes in living situations or family dynamics that require genuine adaptation. The Moon Dasha's deepest ask is for genuine emotional honesty — the willingness to acknowledge what is genuinely felt.",

    Mars: "The Mars Dasha asks the native to engage directly with effort, courage, and the capacity for decisive action. Over its seven years, the natal Mars is activated and becomes the primary energy operating in the life. Property, siblings, physical health, and competitive arenas tend to become active. The body tends to be an important arena during Mars Dasha — physical engagement, whether through work, sport, or illness, becomes significant. The sadhana direction is whether the native can direct energy consciously — whether effort and drive serve genuinely meaningful purposes.",

    Rahu: "Rahu's Dasha — eighteen years — is characterised by amplification, unusual experience, and engagement with what is new, foreign, or unconventional. The sign and house of natal Rahu, and particularly the condition of Rahu's dispositor, shape the character of this period significantly. Common themes include encounters with unusual situations, rapid changes in circumstances, a heightened intensity of desire, and the possibility of significant worldly achievement. The shadow of Rahu Dasha is the possibility of being consumed by amplified desire and losing inner orientation. The sadhana direction is maintaining genuine inner grounding through the amplification.",

    Jupiter: "Jupiter's Dasha brings the themes of wisdom, expansion, dharma, and genuine growth to the foreground over its sixteen years. The natal condition of Jupiter shapes how this expansive principle expresses itself. Teaching, philosophy, children, spiritual practice, and genuinely dharmic endeavours may become prominent. The period often brings encounters with genuine teachers or wisdom traditions. The shadow of Jupiter Dasha is the possibility of comfortable expansion without genuine depth. The sadhana direction is engaging genuinely with the opportunities for dharmic development the period offers.",

    Saturn: "Saturn's Dasha — nineteen years of sustained engagement with discipline, responsibility, and honest reckoning with karma — is perhaps the most characterful of all the major periods. The natal condition of Saturn shapes how this demanding and ultimately developmental energy expresses itself. Work, responsibility, and the confrontation of what is real rather than what is comfortable tend to become primary. The period often deepens with time: what is resisted in its early years is usually better met as the period progresses. The sadhana direction is engaging consciously and patiently with Saturn's demands rather than resisting them.",

    Mercury: "Mercury's Dasha brings the themes of intelligence, communication, learning, and discriminating awareness to the foreground over its seventeen years. Business, writing, teaching, analytical work, and intellectual pursuits may come to the foreground. The period often involves a significant deepening of the native's communicative and analytical capacities. The shadow of Mercury Dasha is the possibility of restlessness — the mind's tendency to move quickly and lose depth. The sadhana direction is developing genuine discriminating wisdom alongside the communicative and analytical facility.",

    Ketu: "Ketu's Dasha — seven years oriented toward completion, detachment, and the spiritual depths — tends to be one of the most inward of the major periods. Worldly ambitions may feel less compelling; past-life themes and the genuine pull toward spiritual practice may become prominent. There is often a quality of shedding during this period — relationships, situations, or self-structures that have been outgrown can be released naturally. The shadow of Ketu Dasha is a possible sense of aimlessness if the native lacks genuine spiritual orientation. The sadhana direction is honouring the pull toward inner life and allowing the shedding to happen consciously.",

    Venus: "Venus's Dasha — the longest at twenty years — brings the themes of relationship, creativity, beauty, and the refinement of experience to the foreground over an extended arc of time. Partnerships, creative work, pleasure, and the quality of sensory and relational experience tend to become particularly significant. Venus Dasha offers a genuine opportunity for the deepening of relational understanding and creative expression over a span of years long enough to see real development. The shadow is the possibility of indulgence without deeper development. The sadhana direction is allowing the relational and aesthetic experiences the period offers to point toward what is genuinely beautiful and genuinely worth valuing.",
  },

  yogaReadings: {
    rajaYoga: "Raja Yoga forms when a Kendra lord (1st, 4th, 7th, or 10th house) and a Kona lord (1st, 5th, or 9th house) come together — through conjunction in the same house or through mutual 7th aspect. The joining of Kendra (the capacity for effective worldly action) and Kona (the direction of dharmic purpose) indicates a confluence of practical capacity and meaningful direction. The 1st house lord is particularly significant in Raja Yoga because it counts as both Kendra and Kona. The strength of any Raja Yoga depends entirely on the condition of the participating planets — their dignity, the aspects they receive, the houses they occupy, and their activation through Dasha periods. A Raja Yoga between well-placed planets in a strong Dasha period produces genuinely significant results; the same structural configuration with challenged planets asks for the patient development of the capacity rather than its immediate expression.",

    dhanaYoga: "Dhana Yoga forms when the lords of the wealth-indicating houses — primarily the 2nd and the 11th — connect through conjunction or mutual aspect, or when lords of the broader wealth group (1st, 2nd, 5th, 9th, and 11th houses) combine. The classical understanding is that these house connections create structural conditions in the chart favourable to the accumulation of resources — not as destiny but as terrain. The 5th house of intelligence and past-life merit and the 9th house of dharma and grace both carry wealth implications in Jyotish because genuine prosperity tends to flow through the application of intelligence and the alignment of action with dharmic direction. The dignity and strength of the participating planets determine the depth of expression.",

    viparitaRajaYoga: "Vipareeta Raja Yoga — literally reverse royal combination — is one of the most paradoxical yogas in classical Jyotish. It forms when lords of the Dusthana houses (6th, 8th, and 12th) are placed in each other's houses or conjunct each other. The classical reasoning is that when the lords of challenge, hidden things, and dissolution are confined within each other's domains, the challenging energy is in some sense contained — the rest of the chart is released from some of its pressure. This yoga often manifests as gains through others' difficulties, strength that emerges from circumstances of apparent constraint or loss, or the capacity to transform adversity into advantage. Its expression is genuinely complex and it is one of the most commonly misunderstood yogas in popular Jyotish. Assessment by a qualified practitioner is recommended before drawing conclusions about its specific expression.",

    panchaMahapurusha: "Pancha Mahapurusha Yoga — one of five classical yogas, each formed when a specific planet is in its own sign or exaltation and placed in a Kendra house (1st, 4th, 7th, or 10th). The five types are Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), and Shasha (Saturn). Each indicates a developed, structured expression of that planet's highest qualities in the life. Ruchaka indicates courage, physical and moral vitality, and the capacity for decisive right action — strength that serves rather than dominates. Bhadra indicates intellectual clarity and discriminating communication — the ability to perceive accurately and express that perception with precision and care. Hamsa indicates wisdom and dharmic conduct — a natural orientation toward what is genuinely true and genuinely right, expressed through teaching, counsel, or simply through the quality of how one lives. Malavya indicates refined values and the capacity for genuine relationship — beauty understood not merely as aesthetics but as the ability to recognise and participate in what is genuinely worth valuing. Shasha indicates disciplined, durable strength built through sustained effort — authority that is earned through endurance and integrity rather than claimed through assertion. As with all Yogas, the presence of this configuration indicates potential and natural orientation — not guaranteed outcome. The dasha activation of the yoga planet, the aspects it receives, and the overall strength of the chart all determine how fully this potential finds expression in a life.",

    guruMangalaYoga: "Guru Mangala Yoga forms when Jupiter and Mars are conjunct — in the same house — or in mutual 7th aspect, each directly facing the other across the chart. The combination joins the two most characteristically purposeful forces in the planetary system: Mars, the planet of directed energy and courageous action; and Jupiter, the planet of wisdom, dharma, and meaningful expansion. Together they create a configuration associated with the capacity to act from genuine principle — courage that is oriented by wisdom, and wisdom that is expressed through courageous action. This yoga is classically associated with martial and spiritual courage simultaneously — the capacity to engage with genuine difficulty from a place of genuine understanding. Its expression depends on the dignity and house placement of both planets.",

    neechaBhangaRajaYoga: "Neecha Bhanga Raja Yoga — the cancellation of debilitation and its conversion into unusual strength — is one of the most complex configurations in classical Jyotish. A planet in its debilitation sign faces its greatest structural challenge. Classical texts describe specific conditions under which this debilitation is cancelled: the lord of the debilitation sign being in a Kendra from the Lagna or Moon, the planet that is exalted in the debilitation sign being in a Kendra, or the debilitated planet being aspected by its sign lord. When these conditions are genuinely met, the debilitated planet's energy may transform into unusual strength — the friction of the debilitation, when the structural conditions for cancellation are present, produces a quality of strength through adversity that is more durable than the strength of easy placement. Assessment of this yoga requires careful examination of the complete chart by a qualified practitioner.",
  },

  dignityLabels: {
    exalted:     "Exalted — the planet operates at heightened capacity in this sign.",
    own:         "Own Sign — the planet is in its home territory; it operates with natural ease.",
    friendly:    "Friendly Sign — the planet operates in a supportive environment.",
    neutral:     "Neutral Sign — the planet operates without particular support or friction from the sign.",
    enemy:       "Enemy Sign — the planet operates with some friction in this sign; it must work harder.",
    debilitated: "Debilitated — the planet is in its weakest sign; its qualities face structural challenge.",
  },

  closingNote: "This reading is a framework for honest reflection — not a verdict about your life or a fixed description of who you are. The chart shows the terrain your consciousness is navigating in this life. How you navigate it is always your own. For personalised interpretation, consult a qualified Jyotish practitioner. For specific remedies, consult an experienced Pandit. For sadhana, begin with the basic practices in the Sadhana Path section of this site.",

};
